import 'package:objectbox/objectbox.dart';

@Entity() // called when defining a class(field) to be stored in ObjectBox
@Sync()
class TodoItem {
  int id;
  String date;
  String time;
  String description;

  TodoItem({
    this.id = 0, // id not required, as it will be auto-generated by ObjectBox
    required this.date,
    required this.time,
    required this.description,
  });
}
